# Generated by Django 5.1.5 on 2025-02-06 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfileModel',
            fields=[
                ('LicenseNumber', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Specialization', models.TextField()),
                ('gender', models.CharField(max_length=20, null=True)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='ProfilePic')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_created=True, auto_now=True, null=True)),
                ('SensitiveInformation', models.TextField(null=True)),
                ('HospitalName', models.CharField(max_length=100, null=True)),
                ('Symptoms', models.TextField(null=True)),
                ('Diagnosis', models.CharField(max_length=100, null=True)),
                ('TestsConducted', models.TextField(null=True)),
                ('TreatmentPlan', models.TextField(null=True)),
                ('AdditionalNotes', models.TextField(null=True)),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.doctorprofilemodel')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileModel',
            fields=[
                ('MedicalID', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('DateOfBirth', models.DateField(null=True)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Non-Binary', 'Non-Binary'), ('Perfer not to say', 'Perfer not to say')], max_length=20, null=True)),
                ('Age', models.PositiveIntegerField(null=True)),
                ('PhoneNumber', models.CharField(max_length=13, null=True)),
                ('Address', models.TextField(null=True)),
                ('Country', models.CharField(max_length=30, null=True)),
                ('QRCode', models.ImageField(blank=True, null=True, upload_to='QRCode')),
                ('ProfilePic', models.ImageField(blank=True, null=True, upload_to='ProfilePic')),
                ('MedicalRecord', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.medicalrecordmodel')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
