# Generated by Django 5.1.5 on 2025-02-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_userprofilemodel_id_alter_userprofilemodel_medicalid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='MedicalID',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
