# Generated by Django 5.1.5 on 2025-02-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_userprofilemodel_medicalid'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofilemodel',
            name='Degree',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='MedicalRecord',
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='MedicalRecord',
            field=models.ManyToManyField(blank=True, null=True, to='backend.medicalrecordmodel'),
        ),
    ]
