# Generated by Django 5.1.5 on 2025-02-09 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_tagmodel_blogmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='MedicalRecord',
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='MedicalRecord',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.medicalrecordmodel'),
        ),
    ]
