# Generated by Django 5.1.5 on 2025-02-09 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_userprofilemodel_medicalrecord_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='MedicalRecord',
        ),
        migrations.AddField(
            model_name='medicalrecordmodel',
            name='UserProfile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='backend.userprofilemodel'),
        ),
    ]
