# Generated by Django 5.1.5 on 2025-02-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_remove_userprofilemodel_medicalrecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='Likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
