# Generated by Django 5.1.5 on 2025-02-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_blogmodel_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofilemodel',
            name='HospitalName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='CreatedAt',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
