# Generated by Django 5.0.4 on 2025-02-12 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_blogmodel_createdat'),
        ('backend', '0009_doctorprofilemodel_hospitalname_and_more'),
    ]

    operations = [
    ]
