# Generated by Django 5.1.6 on 2025-02-12 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_merge_20250212_0503'),
        ('backend', '0010_merge_20250212_0921'),
    ]

    operations = [
    ]
