# Generated by Django 5.1.6 on 2025-02-13 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_alter_userprofilemodel_guadian1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofilemodel',
            name='Location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofilemodel',
            name='ProfilePic',
            field=models.ImageField(blank=True, null=True, upload_to='Doctorpic'),
        ),
    ]
