# Generated by Django 5.1.6 on 2025-02-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_doctorprofilemodel_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofilemodel',
            name='ProfilePic',
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='Link',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
