# Generated by Django 5.1.6 on 2025-02-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_remove_doctorprofilemodel_profilepic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAppointmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctor', models.CharField(max_length=20, null=True)),
                ('Patient', models.CharField(max_length=10, null=True)),
                ('Date', models.DateField(null=True)),
                ('Time', models.TimeField(null=True)),
                ('Status', models.CharField(max_length=10, null=True)),
                ('Reason', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='doctorprofilemodel',
            name='Bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
